### ISSUE TITLE
incorrect travis config file

### ISSUE THREAD

**Issue by cherukumilli** [biztek/pmp-help#1]
You should not include element dependencies in travis config file like:

```
- bower install paper-icon-button
```

**Comment by sricharan123** [comment]
included in bower.json , removed from travis config file. thanks.

**Comment by cherukumilli** [comment]
@sricharan123 
Is there any reason you need to put your access_key info in the travis config file

```
  sauce_connect:
    username: "sricharanBiztek"
    access_key: "d1b09f87-c78b-4b54-8097-202bb3b18c52"
```

**Comment by sricharan123** [comment]
@rajkumarajce 
fixed. please review and close. thanks.
