### ISSUE TITLE
bower.json - non standard dependencies for iron-icon and iron-icons...

### ISSUE THREAD

**Issue by cherukumilli** [biztek/pmp-help#10]
In dependencies section, you are using `~` for some dependencies and `^` for some other dependencies. Please either use a ~ or a ^ but not both. You want to fix the dependency to a hard version then do not use either of the symbols. Please read up on `semver` for details on what these symbols mean.

Please remove the following lines:

```
    "iron-icon": "PolymerElements/iron-icon#~1.0.7",
    "iron-icons": "PolymerElements/iron-icons#~1.1.2",
``

and

reinstall them using 
```

bower install PolymerElements/iron-icon --save
bower install PolymerElements/iron-icons --save

```
```

**Comment by sricharan123** [comment]
fixed

**Comment by cherukumilli** [comment]
@rajkumarajce 
Please review
