### ISSUE TITLE
_getFileContent should return a promise...

### ISSUE THREAD

**Issue by cherukumilli** [biztek/pmp-help#7]
_getFileContent should return a promise.

`_toggleDialog` should wait for the promise to return instead of using the async call.

**Comment by sricharan123** [comment]
@cherukumilli 
changes made in pmp-help, please go through it. thanks.

**Comment by cherukumilli** [comment]
@sricharan123 
- [ ] Please remove the `console.log` statement

```
console.log("filename:" + fileName);
```
- [ ] Please change the following 

from:

```
console.log(error);
```

to

```
console.error(error);
```
- [x] Please remove the coloring of the button (you are showing a paper-toast, so there is no need to give them another visual indication)

```
this.$.help.style.color = 'red';
```
- [x] Please expose `toastDuration`. rename `_toastDuration` to `toastDuration` in the entire file.

**Comment by sricharan123** [comment]
@rajkumarajce 
code review fixed.
