### ISSUE TITLE
Readme file need to be updated to show how to use the element

### ISSUE THREAD

**Issue by cherukumilli** [biztek/pmp-help#8]
Please use `paper-input`'s read me file as a template

Also, the path to biztek below is wrong. It should be in lower case.

```
$ bower install — save Biztek/pmp-help
```

**Comment by cherukumilli** [comment]
@sricharan123 
README.md file still says `the help icon color changes to red.`
Is this correct? If not, please correct it.

**Comment by sricharan123** [comment]
@rajkumarajce 
fixed.

**Comment by rajkumarajce** [comment]
@sricharan123  kindly remove the text 'following'

**Comment by sricharan123** [comment]
done
