### ISSUE TITLE
Layout is not imported even though it is used and a few other issues...

### ISSUE THREAD

**Issue by cherukumilli** [biztek/pmp-help#9]
**Problem 1:**
- [x] In line #L20 and #L21 you are trying to use the layouts from `iron-flex-layout` but you are not importing this element.
- [x] `bower.json` also doesn't include `iron-flex-layout`

**Problem 2:**
- [x] Why do you need to use a layout here in the first place?

**Problem 3:**
- [x] on Line #L25 to #L28. Why do we need this code? If you need the user to set the `max-width` then you should expose it as a custom property. Please look at `paper-input` or other elements to see how to expose custom properties.

**Problem 4**
- [x] on Line #L30 to #L32. Why do we need to color this? If we need to set a default color then you should set it with a custom property and expose it at the same time.

**Problem 5***
- [x]  Please expose `title`. You can set its default value to `help` but you should expose it via a simple property

**Problem 6**
- [x] why is the entire code wrapped in a div and section? what if we remove the top level div and section?

**Problem 7**
- [x] On line #L42, you use a `div` with `class="buttons"`. Why do we need a div here? Also class `buttons` is not defined anywhere in the code.

**Comment by sricharan123** [comment]
@cherukumilli 
i used colors specific to that project, but i have to expose the custom property, 
can i use example:
#help {
      color: var(--help-icon-color, --paper-indigo-500);
    }
so that if want to change the default color in pmp-ui then we can override like

--help-icon-color:red;

**Comment by cherukumilli** [comment]
@sricharan123 
Yes. 
A small change in the naming convention. 
Please change the variable name from `--help-icon-color` to `--pmp-help-icon-color`. 
This will prevent naming conflicts with other elements if they end up using the same name as your element.

Also, if you are planning to use a variable like `--paper-indigo-500` in your custom element then you should import the file that has the definition of `--paper-indigo-500`

**Comment by sricharan123** [comment]
@cherukumilli 
on problem 7
div with class="buttons"  is in paper-dialog-behaviour which paper-dialog is using.( css properties applies by parent.),

**Comment by cherukumilli** [comment]
@sricharan123 
Please go ahead and include the following import if you want to use `class="buttons"`

```
<link rel="import" href="../paper-dialog-behavior/paper-dialog-shared-styles.html">
```

**Comment by sricharan123** [comment]
@cherukumilli 
sorry , i just confused, paper-dialog is already implementing paper-dialog-behavior and including paper-dialog-shared-styles.html,
 we are using paper-dialog(that includes all)  in our pmp-help custom element, do we need to again explicitly include with import statement. (because we are directly using that property class="buttons" in our custom element, thats why we need to import explicitly.) thanks.

**Comment by cherukumilli** [comment]
@sricharan123 
Yes. You are right, we DON'T need to import `paper-dialog-shared-styles.html`. Pls **ignore** my earlier suggestion https://github.com/biztek/pmp-help/issues/9#issuecomment-253328738

btw: only Line 17, you have the following:

```
    <style is="custom-style">
```

Why do we need a `custom-style` here?

**Comment by sricharan123** [comment]
@cherukumilli 
my mistake inside dom-module just style is enough , i will remove.

**Comment by sricharan123** [comment]
fixed.

**Comment by cherukumilli** [comment]
@rajkumarajce 
Please review
